import { LegalPageLayout } from "@/components/legal-page-layout"

export const metadata = { title: "Terms & Conditions" }

export default function TermsPage() {
    return (
        <LegalPageLayout title="Terms & Conditions" lastUpdated="April 10, 2026">
            <h2>1. Introduction</h2>
            <p>Welcome to Clorefy (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). Clorefy is an AI-powered document generation platform accessible at <a href="https://clorefy.com">clorefy.com</a> that enables users to create invoices, contracts, quotations, and proposals through conversational AI prompts.</p>
            <p>By accessing or using our website and services, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use our services.</p>

            <h2>2. Definitions</h2>
            <ul>
                <li><strong>&quot;Service&quot;</strong> refers to the Clorefy platform, including all features for AI-powered document generation, editing, exporting, and e-signatures.</li>
                <li><strong>&quot;User&quot;</strong> or <strong>&quot;You&quot;</strong> refers to any individual or entity that accesses or uses the Service.</li>
                <li><strong>&quot;Subscription&quot;</strong> refers to the paid plans (Starter, Pro, Agency) that provide access to premium features.</li>
                <li><strong>&quot;Documents&quot;</strong> refers to invoices, contracts, quotations, proposals, and any other content generated through the Service.</li>
            </ul>

            <h2>3. Service Description</h2>
            <p>Clorefy provides AI-powered document generation for businesses across 11 countries. Users describe their document needs in natural language, and our AI generates professionally formatted, country-specific compliant documents. The Service includes:</p>
            <ul>
                <li>AI-powered generation of invoices, contracts, quotations, and proposals</li>
                <li>Country-specific tax compliance and formatting</li>
                <li>Document editing and customization</li>
                <li>PDF, DOCX, and image export</li>
                <li>Digital signature workflows</li>
                <li>9 professional template styles</li>
            </ul>

            <h2>4. AI-Generated Content Disclaimer</h2>
            <p><strong>IMPORTANT:</strong> All documents generated by Clorefy are produced using artificial intelligence. While we strive for accuracy, AI-generated content may contain errors, inaccuracies, or omissions. Users are solely responsible for:</p>
            <ul>
                <li>Reviewing all AI-generated documents before use, distribution, or signing</li>
                <li>Verifying the accuracy of all calculations, tax rates, legal terms, and compliance requirements</li>
                <li>Ensuring documents meet their specific legal and regulatory requirements</li>
                <li>Consulting qualified legal, tax, or financial professionals when necessary</li>
            </ul>
            <p><strong>Clorefy is not liable for any errors, omissions, or inaccuracies in AI-generated content.</strong> Documents should be treated as drafts requiring human review and approval before being used for any legal, financial, or business purpose.</p>

            <h2>5. Account Registration</h2>
            <p>To use the Service, you must create an account by providing accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.</p>

            <h2>6. Subscription Plans and Billing</h2>
            <p>Clorefy offers the following subscription tiers:</p>
            <ul>
                <li><strong>Free:</strong> 3 documents/month, 10 messages/document, Invoice and Contract types only</li>
                <li><strong>Starter (₹749/month or ₹599/month billed yearly):</strong> 50 documents/month, 25 messages/document, all document types</li>
                <li><strong>Pro (₹1,999/month or ₹1,599/month billed yearly):</strong> 150 documents/month, 30 messages/document, all document types, priority support</li>
                <li><strong>Agency (Coming Soon):</strong> Unlimited documents and messages</li>
            </ul>
            <p>Subscriptions are billed in advance on a monthly or yearly basis. All prices are in Indian Rupees (INR) and are inclusive of applicable taxes unless stated otherwise.</p>

            <h2>7. Payment Processing</h2>
            <p>Payments are processed securely through Razorpay, a PCI-DSS compliant payment gateway. We do not store your credit card or debit card details on our servers. By making a payment, you agree to Razorpay&apos;s terms of service.</p>

            <h2>8. Intellectual Property</h2>
            <p>Documents you create using Clorefy belong to you. However, the Clorefy platform, including its software, design, AI models, templates, and branding, remains our intellectual property. You may not copy, modify, distribute, or reverse-engineer any part of the platform.</p>

            <h2>9. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
                <li>Generate fraudulent, misleading, or illegal documents</li>
                <li>Impersonate any person or entity</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Use automated tools to scrape or extract data from the Service</li>
            </ul>

            <h2>10. Data Privacy</h2>
            <p>Your use of the Service is also governed by our <a href="/privacy">Privacy Policy</a>. We collect and process personal data as described therein.</p>

            <h2>11. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Clorefy shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to damages arising from AI-generated content errors, service interruptions, or data loss.</p>
            <p>Our total liability for any claim shall not exceed the amount you paid for the Service in the 12 months preceding the claim.</p>

            <h2>12. Termination</h2>
            <p>We may suspend or terminate your account if you violate these Terms. You may cancel your subscription at any time through your account settings. Upon cancellation, you retain access until the end of your current billing period.</p>

            <h2>13. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Kolkata, West Bengal, India.</p>

            <h2>14. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes via email or through the Service. Continued use after changes constitutes acceptance.</p>

            <h2>15. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:support@clorefy.com">support@clorefy.com</a> or visit our <a href="/contact">Contact page</a>.</p>
        </LegalPageLayout>
    )
}
