/**
 * DOCX Export Utility
 * Generates a Word document from InvoiceData (and new document type data) using the `docx` package.
 * Works client-side — no server required.
 */

import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle,
  ShadingType, convertInchesToTwip, Header, Footer,
  PageNumber, NumberFormat,
} from "docx"
import type { InvoiceData } from "@/lib/invoice-types"
import { getDocumentTypeConfig } from "@/lib/document-type-registry"
import type {
  SOWData,
  ChangeOrderData,
  NDAData,
  ClientOnboardingFormData,
  PaymentFollowupData,
} from "@/lib/document-schemas"

// ─── Formatting helpers ────────────────────────────────────────────────────

function fmtMoney(n: number, currency = "USD"): string {
  const symbols: Record<string, string> = {
    USD: "$", EUR: "EUR ", GBP: "GBP ", INR: "Rs.", AUD: "A$",
    CAD: "C$", SGD: "S$", AED: "AED ", PHP: "PHP ", ZAR: "R",
  }
  const sym = symbols[currency] || currency + " "
  return `${sym}${n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

/** Alias kept for backward compatibility */
function fmt(n: number, currency = "₹"): string {
  return fmtMoney(n, currency)
}

function calcTotals(data: InvoiceData) {
  const items = data.items || []
  const subtotal = items.reduce((s, item) => {
    const base = (Number(item.quantity) || 0) * (Number(item.rate) || 0)
    const disc = item.discount ? base * (Number(item.discount) / 100) : 0
    return s + base - disc
  }, 0)

  const discountValue = Number(data.discountValue) || 0
  const discountAmount = data.discountType === "flat"
    ? discountValue
    : subtotal * (discountValue / 100)

  const afterDiscount = subtotal - discountAmount
  const taxRate = Number(data.taxRate) || 0
  const taxAmount = afterDiscount * (taxRate / 100)
  const shipping = Number(data.shippingFee) || 0
  const total = afterDiscount + taxAmount + shipping

  return { subtotal, discountAmount, taxAmount, shipping, total }
}

// ─── Shared low-level builders ─────────────────────────────────────────────

function cell(text: string, opts: {
  bold?: boolean
  shade?: boolean
  align?: (typeof AlignmentType)[keyof typeof AlignmentType]
  width?: number
} = {}): TableCell {
  return new TableCell({
    children: [new Paragraph({
      alignment: opts.align ?? AlignmentType.LEFT,
      children: [new TextRun({ text, bold: opts.bold, size: 20, font: "Calibri" })],
    })],
    shading: opts.shade ? { type: ShadingType.SOLID, color: "F5F5F5" } : undefined,
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: "E5E5E5" },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E5E5" },
      left: { style: BorderStyle.NONE },
      right: { style: BorderStyle.NONE },
    },
  })
}

function labelValue(label: string, value: string): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 20, font: "Calibri", color: "555555" }),
      new TextRun({ text: value || "—", size: 20, font: "Calibri" }),
    ],
  })
}

function sectionHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 100 },
    children: [new TextRun({ text, bold: true, size: 26, font: "Calibri", color: "1A1A1A" })],
  })
}

function bodyText(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    children: [new TextRun({ text, size: 20, font: "Calibri", color: "333333" })],
  })
}

function bulletItem(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 40 },
    bullet: { level: 0 },
    children: [new TextRun({ text, size: 20, font: "Calibri" })],
  })
}

function separator(): Paragraph {
  return new Paragraph({ spacing: { after: 120 }, children: [] })
}

function docFooter(): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Generated by Clorefy · clorefy.com", size: 16, font: "Calibri", color: "AAAAAA" })],
  })
}

function makePartyCell(heading: string, lines: string[]): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        spacing: { after: 60 },
        children: [new TextRun({ text: heading, bold: true, size: 22, font: "Calibri", color: "555555", allCaps: true })],
      }),
      ...lines.map(l => new Paragraph({
        spacing: { after: 40 },
        children: [new TextRun({ text: l, size: 20, font: "Calibri" })],
      })),
    ],
    borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
    width: { size: 50, type: WidthType.PERCENTAGE },
    margins: { top: 0, bottom: 0, left: 0, right: 0 },
  })
}

function partiesTable(fromLabel: string, fromLines: string[], toLabel: string, toLines: string[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [new TableRow({ children: [makePartyCell(fromLabel, fromLines), makePartyCell(toLabel, toLines)] })],
    borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
  })
}

function assembleDoc(title: string, docType: string, children: (Paragraph | Table)[]): Document {
  return new Document({
    creator: "Clorefy",
    title,
    description: `${docType} generated by Clorefy`,
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left: convertInchesToTwip(1.2),
            right: convertInchesToTwip(1.2),
          },
        },
      },
      children,
    }],
  })
}

// ─── Invoice / Quote / Proposal / Receipt / Contract DOCX ─────────────────
// (Original InvoiceData-based export — handles invoice, quote, contract, proposal)

function generateInvoiceFamilyDocx(data: InvoiceData): Document {
  const docType = data.documentType || "Invoice"
  const typeConfig = getDocumentTypeConfig(docType)
  const typeLabel = typeConfig?.label || docType
  const currency = data.currency || "₹"
  const { subtotal, discountAmount, taxAmount, shipping, total } = calcTotals(data)

  const refNumber = data.invoiceNumber || data.referenceNumber || ""
  const title = `${typeLabel}${refNumber ? ` — ${refNumber}` : ""}`

  const headerParagraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
  ]

  const fromLines = [data.fromName, data.fromEmail, data.fromPhone, data.fromAddress].filter(Boolean) as string[]
  const toLines = [data.toName, data.toEmail, data.toPhone, data.toAddress].filter(Boolean) as string[]

  const partyTbl = partiesTable("From", fromLines, "To", toLines)

  const dateParagraphs: Paragraph[] = []
  if ((data as any).invoiceDate) dateParagraphs.push(labelValue("Date", (data as any).invoiceDate))
  if (data.dueDate) dateParagraphs.push(labelValue("Due Date", data.dueDate))
  if (data.paymentTerms) dateParagraphs.push(labelValue("Payment Terms", data.paymentTerms))
  if (data.referenceNumber && data.referenceNumber !== refNumber) dateParagraphs.push(labelValue("Reference", data.referenceNumber))

  const hasItems = Array.isArray(data.items) && data.items.length > 0
  const itemsTable = hasItems ? new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: [
          cell("Description", { bold: true, shade: true, width: 50 }),
          cell("Qty", { bold: true, shade: true, align: AlignmentType.CENTER, width: 10 }),
          cell("Rate", { bold: true, shade: true, align: AlignmentType.RIGHT, width: 20 }),
          cell("Amount", { bold: true, shade: true, align: AlignmentType.RIGHT, width: 20 }),
        ],
      }),
      ...(data.items || []).map(item => {
        const qty = Number(item.quantity) || 0
        const rate = Number(item.rate) || 0
        const disc = item.discount ? rate * qty * (Number(item.discount) / 100) : 0
        const amount = qty * rate - disc
        return new TableRow({
          children: [
            cell(item.description || "", { width: 50 }),
            cell(String(qty), { align: AlignmentType.CENTER, width: 10 }),
            cell(fmt(rate, currency), { align: AlignmentType.RIGHT, width: 20 }),
            cell(fmt(amount, currency), { align: AlignmentType.RIGHT, width: 20 }),
          ],
        })
      }),
    ],
  }) : null

  const totalRows: Paragraph[] = []
  const addTotal = (label: string, value: string, bold = false) =>
    totalRows.push(new Paragraph({
      alignment: AlignmentType.RIGHT,
      spacing: { after: 60 },
      children: [
        new TextRun({ text: `${label}: `, bold, size: 20, font: "Calibri", color: bold ? "1A1A1A" : "555555" }),
        new TextRun({ text: value, bold, size: bold ? 24 : 20, font: "Calibri" }),
      ],
    }))

  if (hasItems) {
    addTotal("Subtotal", fmt(subtotal, currency))
    if (discountAmount > 0) addTotal("Discount", `-${fmt(discountAmount, currency)}`)
    if (taxAmount > 0) addTotal(`Tax (${data.taxRate}%)`, fmt(taxAmount, currency))
    if (shipping > 0) addTotal("Shipping", fmt(shipping, currency))
    addTotal("Total", fmt(total, currency), true)
  }

  const noteParagraphs: Paragraph[] = []
  if (data.notes) {
    noteParagraphs.push(
      new Paragraph({ spacing: { before: 240, after: 80 }, children: [new TextRun({ text: "Notes", bold: true, size: 22, font: "Calibri" })] }),
      new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: data.notes, size: 20, font: "Calibri", color: "555555" })] }),
    )
  }
  if (data.terms) {
    noteParagraphs.push(
      new Paragraph({ spacing: { before: 200, after: 80 }, children: [new TextRun({ text: "Terms & Conditions", bold: true, size: 22, font: "Calibri" })] }),
      new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: data.terms, size: 20, font: "Calibri", color: "555555" })] }),
    )
  }

  const children: (Paragraph | Table)[] = [
    ...headerParagraphs,
    partyTbl,
    separator(),
    ...dateParagraphs,
    separator(),
    ...(itemsTable ? [itemsTable, separator()] : []),
    ...totalRows,
    ...noteParagraphs,
    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, typeLabel, children)
}

// ─── SOW DOCX ──────────────────────────────────────────────────────────────

function generateSOWDocx(data: SOWData): Document {
  const title = `Statement of Work${data.referenceNumber ? ` — ${data.referenceNumber}` : ""}${data.title ? `: ${data.title}` : ""}`
  const currency = data.currency || "USD"

  const fromLines = [data.fromName, data.fromEmail, data.fromAddress].filter(Boolean) as string[]
  const toLines = [data.toName, data.toEmail, data.toAddress].filter(Boolean) as string[]

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
    partiesTable("Provider", fromLines, "Client", toLines),
    separator(),
    labelValue("Effective Date", data.effectiveDate),
    ...(data.endDate ? [labelValue("End Date", data.endDate)] : []),
    ...(data.totalValue != null ? [labelValue("Total Value", fmtMoney(data.totalValue, currency))] : []),
    separator(),

    // Project Overview
    sectionHeading("Project Overview"),
    bodyText(data.projectOverview),
    separator(),

    // Scope of Work
    sectionHeading("Scope of Work"),
    ...(data.scopeItems || []).map(item =>
      new Paragraph({
        spacing: { after: 40 },
        bullet: { level: 0 },
        children: [
          new TextRun({ text: item.title, bold: true, size: 20, font: "Calibri" }),
          ...(item.description ? [new TextRun({ text: ` — ${item.description}`, size: 20, font: "Calibri" })] : []),
          ...(item.included === false ? [new TextRun({ text: " [Excluded]", size: 20, font: "Calibri", color: "999999" })] : []),
        ],
      })
    ),
    separator(),

    // Deliverables
    ...((data.deliverables || []).length > 0 ? [
      sectionHeading("Deliverables"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            tableHeader: true,
            children: [
              cell("Deliverable", { bold: true, shade: true, width: 55 }),
              cell("Due Date", { bold: true, shade: true, width: 20 }),
              cell("Acceptance Criteria", { bold: true, shade: true, width: 25 }),
            ],
          }),
          ...(data.deliverables || []).map(d => new TableRow({
            children: [
              cell(d.description, { width: 55 }),
              cell(d.dueDate || "—", { width: 20 }),
              cell(d.acceptanceCriteria || "—", { width: 25 }),
            ],
          })),
        ],
      }),
      separator(),
    ] : []),

    // Milestones
    ...((data.milestones || []).length > 0 ? [
      sectionHeading("Milestones"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            tableHeader: true,
            children: [
              cell("Milestone", { bold: true, shade: true, width: 40 }),
              cell("Date", { bold: true, shade: true, width: 20 }),
              cell("Description", { bold: true, shade: true, width: 40 }),
            ],
          }),
          ...(data.milestones || []).map(m => new TableRow({
            children: [
              cell(m.name, { width: 40 }),
              cell(m.date, { width: 20 }),
              cell(m.description || "—", { width: 40 }),
            ],
          })),
        ],
      }),
      separator(),
    ] : []),

    // Assumptions
    ...((data.assumptions || []).length > 0 ? [
      sectionHeading("Assumptions"),
      ...(data.assumptions || []).map(a => bulletItem(a)),
      separator(),
    ] : []),

    // Change Control (standard SOW clause — ties into the Change Order document type)
    sectionHeading("Change Control"),
    bodyText("Any request to modify the scope, deliverables, cost, or timeline described in this Statement of Work must be documented in a signed Change Order before the additional or altered work begins. Work performed outside this SOW without a signed Change Order is not covered by the fees stated here."),
    separator(),

    // Notes & Terms
    ...(data.notes ? [sectionHeading("Notes"), bodyText(data.notes), separator()] : []),
    ...(data.terms ? [sectionHeading("Terms & Conditions"), bodyText(data.terms), separator()] : []),

    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, "Statement of Work", children)
}

// ─── Change Order DOCX ─────────────────────────────────────────────────────

function generateChangeOrderDocx(data: ChangeOrderData): Document {
  const title = `Change Order${data.referenceNumber ? ` — ${data.referenceNumber}` : ""}`
  const currency = data.currency || "USD"

  const fromLines = [data.fromName, data.fromEmail, data.fromAddress].filter(Boolean) as string[]
  const toLines = [data.toName, data.toEmail, data.toAddress].filter(Boolean) as string[]

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
    partiesTable("Provider", fromLines, "Client", toLines),
    separator(),
    labelValue("Change Order #", data.changeOrderNumber),
    labelValue("Effective Date", data.effectiveDate),
    // Show the parent's human-readable reference (e.g. "SOW-2026-07-002") when
    // known. Never print the raw internal parentDocumentId UUID on a client-
    // facing document.
    labelValue("Parent Document", `${data.parentDocumentType.toUpperCase()}${data.parentReferenceNumber ? ` — ${data.parentReferenceNumber}` : ""}`),
    ...(data.timelineImpact ? [labelValue("Timeline Impact", data.timelineImpact)] : []),
    separator(),

    sectionHeading("Description of Changes"),
    bodyText(data.description),
    separator(),

    ...(!data.costImpact ? [bodyText("This change order has no cost impact on the original agreement."), separator()] : []),

    // Additions
    ...((data.additions || []).length > 0 ? [
      sectionHeading("Additions"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({ tableHeader: true, children: [cell("Description", { bold: true, shade: true, width: 75 }), cell("Cost", { bold: true, shade: true, width: 25 })] }),
          ...(data.additions || []).map(a => new TableRow({ children: [cell(a.description, { width: 75 }), cell(a.cost != null ? fmtMoney(a.cost, currency) : "—", { align: AlignmentType.RIGHT, width: 25 })] })),
        ],
      }),
      separator(),
    ] : []),

    // Removals
    ...((data.removals || []).length > 0 ? [
      sectionHeading("Removals"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({ tableHeader: true, children: [cell("Description", { bold: true, shade: true, width: 75 }), cell("Cost Reduction", { bold: true, shade: true, width: 25 })] }),
          ...(data.removals || []).map(r => new TableRow({ children: [cell(r.description, { width: 75 }), cell(r.costReduction != null ? fmtMoney(r.costReduction, currency) : "—", { align: AlignmentType.RIGHT, width: 25 })] })),
        ],
      }),
      separator(),
    ] : []),

    // Modifications
    ...((data.modifications || []).length > 0 ? [
      sectionHeading("Modifications"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({ tableHeader: true, children: [cell("Original", { bold: true, shade: true, width: 35 }), cell("Revised", { bold: true, shade: true, width: 40 }), cell("Cost Impact", { bold: true, shade: true, width: 25 })] }),
          ...(data.modifications || []).map(m => new TableRow({ children: [cell(m.original, { width: 35 }), cell(m.revised, { width: 40 }), cell(m.costImpact != null ? fmtMoney(m.costImpact, currency) : "—", { align: AlignmentType.RIGHT, width: 25 })] })),
        ],
      }),
      separator(),
    ] : []),

    // Cost Impact
    ...(data.costImpact ? [
      sectionHeading("Cost Impact"),
      labelValue("Original Total", fmtMoney(data.costImpact.originalTotal, currency)),
      labelValue("New Total", fmtMoney(data.costImpact.newTotal, currency)),
      labelValue("Difference", fmtMoney(data.costImpact.difference, currency)),
      separator(),
    ] : []),

    ...(data.notes ? [sectionHeading("Notes"), bodyText(data.notes), separator()] : []),
    ...(data.terms ? [sectionHeading("Terms & Conditions"), bodyText(data.terms), separator()] : []),

    bodyText("All other terms and conditions of the original agreement remain in full force and effect. This Change Order becomes binding on both parties upon signature."),

    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, "Change Order", children)
}

// ─── NDA DOCX ──────────────────────────────────────────────────────────────

function generateNDADocx(data: NDAData): Document {
  const title = `Non-Disclosure Agreement${data.referenceNumber ? ` — ${data.referenceNumber}` : ""}`

  const fromLines = [data.fromName, data.fromEmail, data.fromAddress].filter(Boolean) as string[]
  const toLines = [data.toName, data.toEmail, data.toAddress].filter(Boolean) as string[]

  const termText = `${data.termDuration} ${data.termUnit} from ${data.termStart}`

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
    partiesTable("Disclosing Party", fromLines, "Receiving Party", toLines),
    separator(),
    labelValue("Effective Date", data.termStart),
    labelValue("Term", termText),
    labelValue("Governing Law", data.governingLaw),
    separator(),

    // Parties detail (multi-party)
    ...((data.parties || []).length > 0 ? [
      sectionHeading("Parties"),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({ tableHeader: true, children: [cell("Name", { bold: true, shade: true, width: 35 }), cell("Role", { bold: true, shade: true, width: 20 }), cell("Address", { bold: true, shade: true, width: 25 }), cell("Representative", { bold: true, shade: true, width: 20 })] }),
          ...(data.parties || []).map(p => new TableRow({ children: [cell(p.name, { width: 35 }), cell(p.role, { width: 20 }), cell(p.address || "—", { width: 25 }), cell(p.representative || "—", { width: 20 })] })),
        ],
      }),
      separator(),
    ] : []),

    sectionHeading("Definition of Confidential Information"),
    bodyText(data.confidentialInfoDefinition),
    separator(),

    sectionHeading("Obligations"),
    ...(data.obligations || []).map(o => bulletItem(o)),
    separator(),

    ...((data.exclusions || []).length > 0 ? [
      sectionHeading("Exclusions"),
      ...(data.exclusions || []).map(e => bulletItem(e)),
      separator(),
    ] : []),

    ...(data.remedies ? [sectionHeading("Remedies"), bodyText(data.remedies), separator()] : []),
    ...(data.notes ? [sectionHeading("Notes"), bodyText(data.notes), separator()] : []),
    ...(data.terms ? [sectionHeading("Additional Terms"), bodyText(data.terms), separator()] : []),

    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, "NDA", children)
}

// ─── Client Onboarding Form DOCX ───────────────────────────────────────────

function generateClientOnboardingFormDocx(data: ClientOnboardingFormData): Document {
  const title = `Client Onboarding Form${data.referenceNumber ? ` — ${data.referenceNumber}` : ""}`

  const providerLines = [data.fromName, data.fromEmail, data.fromAddress].filter(Boolean) as string[]

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
    partiesTable("Prepared By", providerLines, "Client", [data.clientName, data.clientEmail || "", data.clientPhone || "", data.clientAddress || ""].filter(Boolean)),
    separator(),

    sectionHeading("Client Details"),
    labelValue("Client Name", data.clientName),
    ...(data.clientEmail ? [labelValue("Email", data.clientEmail)] : []),
    ...(data.clientPhone ? [labelValue("Phone", data.clientPhone)] : []),
    ...(data.clientAddress ? [labelValue("Address", data.clientAddress)] : []),
    separator(),

    sectionHeading("Project Information"),
    labelValue("Project Name", data.projectName),
    ...(data.projectDescription ? [bodyText(data.projectDescription)] : []),
    ...(data.timelinePreference ? [labelValue("Timeline Preference", data.timelinePreference)] : []),
    ...(data.budgetRange ? [labelValue("Budget Range", data.budgetRange)] : []),
    separator(),

    ...((data.requirements || []).length > 0 ? [
      sectionHeading("Requirements"),
      ...(data.requirements || []).map(r => bulletItem(r)),
      separator(),
    ] : []),

    ...((data.customQuestions || []).length > 0 ? [
      sectionHeading("Custom Questions"),
      ...(data.customQuestions || []).flatMap(q => [
        new Paragraph({
          spacing: { before: 120, after: 40 },
          children: [new TextRun({ text: q.question, bold: true, size: 20, font: "Calibri" })],
        }),
        new Paragraph({
          spacing: { after: 60 },
          children: [new TextRun({ text: q.answer || "—", size: 20, font: "Calibri", color: "333333" })],
        }),
      ]),
      separator(),
    ] : []),

    ...(data.notes ? [sectionHeading("Notes"), bodyText(data.notes), separator()] : []),

    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, "Client Onboarding Form", children)
}

// ─── Payment Follow-up DOCX ────────────────────────────────────────────────

function generatePaymentFollowupDocx(data: PaymentFollowupData): Document {
  const title = `Payment Follow-up — ${data.invoiceNumber}`

  const fromLines = [data.fromName, data.fromEmail, data.fromAddress].filter(Boolean) as string[]
  const toLines = [data.toName, data.toEmail, data.toAddress].filter(Boolean) as string[]

  const toneLabel: Record<string, string> = {
    polite: "Polite Reminder",
    firm: "Firm Notice",
    urgent: "Urgent Notice",
  }

  const children: (Paragraph | Table)[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
      children: [new TextRun({ text: title, bold: true, size: 36, font: "Calibri", color: "1A1A1A" })],
    }),
    partiesTable("From", fromLines, "To", toLines),
    separator(),

    sectionHeading("Invoice Details"),
    labelValue("Invoice Number", data.invoiceNumber),
    labelValue("Invoice Amount", fmtMoney(data.invoiceAmount, data.invoiceCurrency)),
    labelValue("Due Date", data.dueDate),
    labelValue("Days Overdue", String(data.daysOverdue)),
    labelValue("Reminder Tone", toneLabel[data.reminderTone] || data.reminderTone),
    ...(data.paymentLinkUrl ? [labelValue("Payment Link", data.paymentLinkUrl)] : []),
    separator(),

    sectionHeading("Message"),
    bodyText(data.customMessage),
    separator(),

    ...(data.notes ? [sectionHeading("Notes"), bodyText(data.notes), separator()] : []),

    new Paragraph({ spacing: { after: 400 } }),
    docFooter(),
  ]

  return assembleDoc(title, "Payment Follow-up", children)
}

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Generate a DOCX Blob for any supported document type.
 * Accepts InvoiceData as a catch-all (new types are passed through `data as any`
 * to access their specific fields, since they share the same storage shape).
 */
export async function generateDocx(data: InvoiceData): Promise<Blob> {
  const docType = (data.documentType || "invoice").toLowerCase()

  let doc: Document

  switch (docType) {
    case "sow":
      doc = generateSOWDocx(data as unknown as SOWData)
      break
    case "change_order":
      doc = generateChangeOrderDocx(data as unknown as ChangeOrderData)
      break
    case "nda":
      doc = generateNDADocx(data as unknown as NDAData)
      break
    case "client_onboarding_form":
      doc = generateClientOnboardingFormDocx(data as unknown as ClientOnboardingFormData)
      break
    case "payment_followup":
      doc = generatePaymentFollowupDocx(data as unknown as PaymentFollowupData)
      break
    default:
      // invoice, contract, quote, quotation, proposal, receipt — all use InvoiceData
      doc = generateInvoiceFamilyDocx(data)
      break
  }

  return Packer.toBlob(doc)
}
