"use client"

import { LandingLayout } from "@/components/landing/landing-layout"
import { motion } from "framer-motion"
import { Shield, Lock, Users, Zap, CheckCircle, ArrowRight, Building2, ChevronDown, FileText, Bell, CreditCard, RefreshCw } from "lucide-react"
import Link from "next/link"
import { useState } from "react"

const fadeUp = {
    initial: { opacity: 0, y: 30 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: "-80px" },
    transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] }
}

const builtFeatures = [
    {
        icon: FileText,
        title: "9 document types",
        desc: "Invoice, Contract, Quote, Proposal, SOW, NDA, Change Order, Client Onboarding Form, and Payment Follow-up — all generated by AI from a plain-language prompt."
    },
    {
        icon: Shield,
        title: "Digital e-signatures",
        desc: "Send documents for signing via email. Recipients sign in the browser — no account required. Timestamp, IP, and document hash recorded for every signature."
    },
    {
        icon: CreditCard,
        title: "Payment links on every invoice",
        desc: "Razorpay, Stripe, and Cashfree integrations. Clients click Pay Now directly from the document. Links auto-cancel once paid."
    },
    {
        icon: Bell,
        title: "Automated payment reminders",
        desc: "Once you send an invoice, Clorefy auto-sends follow-up reminders at preset intervals until paid or the link expires. Stops automatically on payment."
    },
    {
        icon: RefreshCw,
        title: "Recurring invoices",
        desc: "Set an invoice to auto-generate weekly, monthly, or quarterly. Sends to the same client automatically — no manual work."
    },
    {
        icon: Lock,
        title: "Row-level security",
        desc: "Every document, message, and business record is isolated by user ID using Supabase RLS. You can only see your own data — no cross-tenant access."
    },
]

const faqs = [
    {
        q: "Who is Clorefy built for?",
        a: "Freelancers, consultants, agencies, and small businesses who create invoices, contracts, or proposals regularly. If you spend time on document admin, Clorefy saves that time."
    },
    {
        q: "Do my clients need a Clorefy account?",
        a: "No. Clients receive a link via email. They can view, download, pay, and sign without creating an account."
    },
    {
        q: "Is my data secure?",
        a: "Yes. All data is stored in Supabase with row-level security. Each user's data is fully isolated. Payments are processed by Razorpay, Stripe, or Cashfree — Clorefy never stores card details."
    },
    {
        q: "Can I use my own branding?",
        a: "Yes. Upload your logo during onboarding (or any time from your profile). It appears on every document you generate, on all plans including free."
    },
    {
        q: "What document types does Clorefy support?",
        a: "Invoice, Contract, Quote, Proposal, Statement of Work (SOW), NDA, Change Order, Client Onboarding Form, and Payment Follow-up. Free plan includes Invoice, Contract, and Quote. Starter, Pro, and Agency unlock all 9."
    },
    {
        q: "Is there a team plan?",
        a: "Agency plan (coming soon) includes 3 team members and unlimited documents. Subscribe to the waitlist on the pricing page to be notified."
    },
]

export default function BusinessPage() {
    const [openFaq, setOpenFaq] = useState<number | null>(null)

    return (
        <LandingLayout>
            <div className="min-h-screen">
                {/* Hero */}
                <section className="relative pt-32 pb-20 px-6 sm:px-10 overflow-hidden bg-[var(--landing-cream)]">
                    <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-white via-[#F5F4F0] to-[#EAE8E3] opacity-90" />
                    <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:32px_32px] [mask-image:radial-gradient(ellipse_70%_50%_at_50%_0%,#000_80%,transparent_100%)] pointer-events-none" />
                    <div className="max-w-5xl mx-auto text-center relative z-10">
                        <motion.div
                            initial={{ opacity: 0, y: 30 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
                        >
                            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-orange-100/80 text-[var(--landing-amber)] font-semibold text-sm mb-8 border border-orange-200/50">
                                <Building2 size={16} />
                                <span>Built for service businesses</span>
                            </div>
                            <h1
                                className="font-display text-5xl sm:text-7xl font-semibold tracking-tighter text-[var(--landing-text-dark)] mb-6 leading-[1.02]"
                                style={{ textShadow: "3px 3px 0px rgba(26,26,26,0.08), 0 8px 24px rgba(26,26,26,0.06)" }}
                            >
                                Documents, payments,<br />
                                <span
                                    className="font-serif italic"
                                    style={{
                                        backgroundImage: "linear-gradient(120deg, #d97757 0%, #e07b39 45%, #b8421c 100%)",
                                        WebkitBackgroundClip: "text",
                                        WebkitTextFillColor: "transparent",
                                        backgroundClip: "text",
                                    }}
                                >
                                    reminders — automated
                                </span>
                            </h1>
                            <p className="text-xl sm:text-2xl text-[var(--landing-text-muted)] max-w-2xl mx-auto mb-12">
                                Describe what you need. Clorefy generates the document, emails it to your client, attaches a payment link, and chases it until paid.
                            </p>
                            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                <Link
                                    href="/auth/signup"
                                    className="group inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-[var(--landing-dark)] text-white font-bold text-base border-[2px] border-[var(--landing-dark)] shadow-[4px_4px_0px_0px_rgba(26,26,26,1)] hover:shadow-[6px_6px_0px_0px_rgba(26,26,26,1)] hover:-translate-y-0.5 transition-all"
                                >
                                    Start free — no card needed
                                    <ArrowRight className="transition-transform group-hover:translate-x-1" size={18} />
                                </Link>
                                <Link
                                    href="/pricing"
                                    className="px-8 py-4 rounded-xl font-bold text-base border-[2px] border-[var(--landing-dark)] bg-transparent hover:bg-[var(--landing-dark)] hover:text-white hover:shadow-[4px_4px_0px_0px_rgba(26,26,26,1)] transition-all"
                                >
                                    View pricing
                                </Link>
                            </div>
                        </motion.div>
                    </div>
                </section>

                {/* What's built */}
                <section className="py-24 px-6 sm:px-10 bg-white">
                    <div className="max-w-6xl mx-auto">
                        <motion.div {...fadeUp} className="text-center mb-16">
                            <h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight leading-[1.05] mb-4">
                                What&apos;s built and working today
                            </h2>
                            <p className="text-lg text-[var(--landing-text-muted)] max-w-xl mx-auto">
                                No roadmap items here — every feature below is live in the app.
                            </p>
                        </motion.div>

                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {builtFeatures.map((feat, i) => (
                                <motion.div
                                    key={feat.title}
                                    initial={{ opacity: 0, y: 20 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: i * 0.07, duration: 0.55 }}
                                    className="p-7 rounded-2xl bg-[var(--landing-cream)] border-[2px] border-[var(--landing-dark)] shadow-[3px_3px_0px_0px_rgba(26,26,26,1)] hover:shadow-[5px_5px_0px_0px_rgba(26,26,26,1)] hover:-translate-y-0.5 transition-all"
                                >
                                    <div className="w-11 h-11 rounded-xl bg-white border border-stone-200 flex items-center justify-center text-[var(--landing-amber)] mb-5 shadow-sm">
                                        <feat.icon size={22} />
                                    </div>
                                    <h3 className="font-display text-lg font-bold mb-2">{feat.title}</h3>
                                    <p className="text-sm text-[var(--landing-text-muted)] leading-relaxed">{feat.desc}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* Security facts */}
                <section className="py-24 px-6 sm:px-10 bg-[var(--landing-cream)]">
                    <div className="max-w-5xl mx-auto">
                        <motion.div {...fadeUp} className="text-center mb-16">
                            <h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight leading-[1.05] mb-4">
                                Security that&apos;s actually built in
                            </h2>
                            <p className="text-lg text-[var(--landing-text-muted)] max-w-xl mx-auto">
                                No certifications, just real technical controls.
                            </p>
                        </motion.div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            {[
                                { icon: Shield, name: "Row-level security on every table", desc: "Supabase RLS — each user sees only their own data" },
                                { icon: Lock, name: "CSRF protection", desc: "HMAC-signed tokens on all state-changing requests" },
                                { icon: Zap, name: "Rate limiting", desc: "Per-user and per-IP limits on all API endpoints" },
                                { icon: CheckCircle, name: "Input sanitization", desc: "XSS prevention and injection blocking on all inputs" },
                                { icon: Shield, name: "E-signature audit trail", desc: "IP, timestamp, and document hash recorded per signature" },
                                { icon: Lock, name: "No card data stored", desc: "Payments processed by Razorpay/Stripe/Cashfree — Clorefy never stores card numbers" },
                            ].map((item, i) => (
                                <motion.div
                                    key={item.name}
                                    initial={{ opacity: 0, y: 15 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: i * 0.05 }}
                                    className="flex items-start gap-4 p-5 rounded-2xl bg-white border border-stone-100 hover:shadow-sm transition-all"
                                >
                                    <div className="w-9 h-9 rounded-xl bg-orange-50 flex items-center justify-center text-[var(--landing-amber)] shrink-0 mt-0.5">
                                        <item.icon size={18} />
                                    </div>
                                    <div>
                                        <p className="font-semibold text-sm text-[var(--landing-text-dark)]">{item.name}</p>
                                        <p className="text-xs text-[var(--landing-text-muted)] mt-0.5">{item.desc}</p>
                                    </div>
                                </motion.div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* FAQ */}
                <section className="py-24 px-6 sm:px-10 bg-white">
                    <div className="max-w-3xl mx-auto">
                        <motion.div {...fadeUp} className="text-center mb-16">
                            <h2 className="font-display text-4xl font-semibold tracking-tight">Common questions</h2>
                        </motion.div>
                        <div className="space-y-3">
                            {faqs.map((faq, i) => (
                                <div key={i} className="border-[2px] border-[var(--landing-dark)] rounded-2xl overflow-hidden shadow-[2px_2px_0px_0px_rgba(26,26,26,1)]">
                                    <button
                                        onClick={() => setOpenFaq(openFaq === i ? null : i)}
                                        className="w-full flex items-center justify-between p-5 text-left font-semibold text-sm hover:bg-[var(--landing-cream)] transition-colors"
                                    >
                                        {faq.q}
                                        <ChevronDown size={18} className={`transition-transform duration-300 shrink-0 ml-4 ${openFaq === i ? "rotate-180" : ""}`} />
                                    </button>
                                    <div
                                        className={`overflow-hidden transition-all duration-300 ${openFaq === i ? "max-h-40 opacity-100" : "max-h-0 opacity-0"}`}
                                    >
                                        <p className="px-5 pb-5 text-sm text-[var(--landing-text-muted)] leading-relaxed">{faq.a}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* CTA */}
                <section className="py-24 px-6 sm:px-10 bg-[var(--landing-cream)]">
                    <motion.div
                        {...fadeUp}
                        className="max-w-4xl mx-auto bg-[var(--landing-dark)] rounded-[2.5rem] p-12 sm:p-20 text-center relative overflow-hidden border-[2px] border-[var(--landing-dark)] shadow-[6px_6px_0px_0px_rgba(26,26,26,1)]"
                    >
                        <h2 className="font-display text-4xl sm:text-5xl text-[var(--landing-cream)] mb-4 font-semibold tracking-tight">
                            Start generating documents<br />
                            <span className="text-[var(--landing-amber)] italic font-serif">for free today</span>
                        </h2>
                        <p className="text-stone-400 text-base mb-8 max-w-lg mx-auto">
                            Free plan · No credit card · Cancel anytime
                        </p>
                        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                            <Link
                                href="/auth/signup"
                                className="group inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-[var(--landing-cream)] text-[var(--landing-dark)] font-bold text-base hover:-translate-y-0.5 hover:shadow-[4px_4px_0px_0px_rgba(255,255,255,0.3)] transition-all"
                            >
                                Get Started Free
                                <ArrowRight className="transition-transform group-hover:translate-x-1" size={18} />
                            </Link>
                            <Link href="/pricing" className="text-stone-400 hover:text-white text-sm font-medium transition-colors">
                                View all plans →
                            </Link>
                        </div>
                    </motion.div>
                </section>
            </div>
        </LandingLayout>
    )
}
